//! Authentication methods.

#[cfg(feature = "approle")]
pub mod approle;
#[cfg(feature = "cert-auth")]
pub mod cert;
#[cfg(feature = "jwt-auth")]
pub mod jwt;
#[cfg(feature = "kerberos-auth")]
pub mod kerberos;
#[cfg(feature = "kubernetes-auth")]
pub mod kubernetes;
#[cfg(feature = "ldap-auth")]
pub mod ldap;
#[cfg(feature = "radius-auth")]
pub mod radius;
#[cfg(feature = "token")]
pub mod token;
#[cfg(feature = "userpass")]
pub mod userpass;
